[package]
name = "spandoc-panic"
version = "0.1.0"
authors = ["teor <teor@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spandoc = "0.2.0"
